dataset_type: CustomDataset
dataset_name: load_digits() #load_breast_cancer, load_digits, load_boston, load_iris, load_diabetes, load_wine
# Train/val parameters split
val_size: 0.3
data_seed: 0

# Dataloader parameters 
graph_size: 'None'
n_batches: 1         # this argument passed into train dataset hence is graph size small then we need to sample many small graphs
train_batch_size: 1   # always which graph_size is none 1
val_batch_size: 1     # always 1  because manually set graph_size = None for validation
num_workers: 4



#transforms: CustomImageDatasetTransforms(cfg)
#target_transform: None


