# Model name (have to be represented in self.model_types in method.py)
type: EdgeNet
edge_generation_type: DynamicEdgeConv_DGM # Types: DynamicEdgeConv, DynamicEdgeConv_DGM
# Model parameters
in_channels: [10, 10]
out_channels: [10, 10]
# have to defire, hence during the initialization values of will be assigned (insize is nodes dim, outsize is number of unique labels) 
insize: None
outsize: None
k: [1, 5, 10]
prob_reg: 0.0001
# Optimizer parameters
opt: 
  lr: 0.004
  warmup_steps_pct: 0.02
  decay_steps_pct: 0.9
  weight_decay: 0.0
  max_epochs: 1000
  scheduler_gamma: 0.5
  loader_batches: None

