defaults:
  - _self_
  - dataloader: dataset
  - model: EdgeNet_DGM        # EdgeNet, gcnNet, EdgeNet_DGM, EdgeNetMINE
  
trainer:
  cuda_number: '2'
  gpus: 1
  is_logger_enabled: True
  num_sanity_val_steps: 5
  check_val_every_n_epoch: 25
  log_every_n_steps: 25

wadb:
  logger_project_name: edge_generation_baselines
  logger_name: None
  entity: edge_generation


seed_everything: 1



